<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Marketing Guide - {{ $business->name }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            line-height: 1.6; 
            color: #333;
            padding: 20px;
            max-width: 800px;
            margin: 0 auto;
        }
        
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 8px;
        }
        
        .header h1 { 
            margin: 0; 
            font-size: 28px;
        }
        
        .header p { 
            margin: 5px 0 0 0; 
            opacity: 0.9;
        }
        
        .section { 
            margin: 25px 0; 
            page-break-inside: avoid;
        }
        
        .section h2 { 
            color: #4a5568; 
            border-bottom: 2px solid #667eea;
            padding-bottom: 5px;
            margin-bottom: 15px;
        }
        
        .tip-box { 
            background: #f7fafc; 
            padding: 15px; 
            border-left: 4px solid #4299e1;
            margin: 15px 0;
            border-radius: 4px;
        }
        
        .action-item { 
            background: #e6fffa; 
            padding: 10px 15px;
            margin: 10px 0;
            border-left: 4px solid #38b2ac;
            border-radius: 4px;
        }
        
        .footer { 
            text-align: center; 
            margin-top: 40px;
            padding: 20px;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #718096;
        }
        
        ul, ol { 
            margin: 10px 0; 
            padding-left: 20px;
        }
        
        li { 
            margin: 5px 0; 
        }
        
        @media print {
            body { 
                padding: 0;
                max-width: 100%;
            }
            
            .header { 
                background: #6c63ff !important;
                -webkit-print-color-adjust: exact;
            }
            
            .tip-box, .action-item {
                -webkit-print-color-adjust: exact;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Marketing Playbook for {{ $business->name }}</h1>
        <p>Generated specifically for your {{ $business->industry }} business</p>
        <p>Created on: {{ now()->format('F j, Y') }}</p>
    </div>
    
    <div class="section">
        <h2>📋 Introduction</h2>
        <div class="tip-box">
            {!! nl2br(e($content['intro'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>🎯 Target Audience Analysis</h2>
        <div class="tip-box">
            {!! nl2br(e($content['target_audience'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>📱 Social Media Strategy</h2>
        <div class="tip-box">
            {!! nl2br(e($content['social_media'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>✉️ Email Marketing</h2>
        <div class="tip-box">
            {!! nl2br(e($content['email_marketing'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>💡 Content Ideas</h2>
        <div class="tip-box">
            {!! nl2br(e($content['content_ideas'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>📢 Advertising Guide</h2>
        <div class="tip-box">
            {!! nl2br(e($content['advertising'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>📊 Metrics & Measurement</h2>
        <div class="tip-box">
            {!! nl2br(e($content['metrics'])) !!}
        </div>
    </div>
    
    <div class="section">
        <h2>🚀 30-Day Action Plan</h2>
        <div class="action-item">
            <strong>Week 1:</strong> Set up social media profiles and claim business listings
        </div>
        <div class="action-item">
            <strong>Week 2:</strong> Create content calendar and start email list
        </div>
        <div class="action-item">
            <strong>Week 3:</strong> Launch first social media campaign
        </div>
        <div class="action-item">
            <strong>Week 4:</strong> Analyze results and adjust strategy
        </div>
    </div>
    
    <div class="footer">
        <p>Generated by BizFlow AI • {{ config('app.url') }}</p>
        <p>This guide was created specifically for {{ $business->name }} on {{ now()->format('F j, Y') }}</p>
    </div>
</body>
</html>